gcp_project_id = "boxwood-spot-424211-j6"
gcp_service_account_key_file_path = "credentials/labgce-service-account-key.json"
gce_instance_name = "labcld"
gce_instance_user = "jul"
gce_ssh_pub_key_file_path = "credentials/labgce-ssh-key.pub"
